---------- AGGREGATE FUNCTIONS -----------

SELECT SUM(ENG) AS TOTAL_ENG_MARKS FROM STUDENT;

SELECT COUNT(FIRSTNAME) AS TOTAL_STUDENTS FROM STUDENT;

SELECT COUNT(*) AS TOTAL_STUDENTS FROM STUDENT;

SELECT COUNT(1) AS TOTAL_STUDENTS FROM STUDENT;

SELECT COUNT(ROLLNO) AS TOTAL_STUDENTS FROM STUDENT;

SELECT MIN(ENG) AS MIN_MARKS_ENG FROM STUDENT;

SELECT MAX(ENG) AS MIN_MARKS_ENG FROM STUDENT;

SELECT AVG(ENG) AS MIN_MARKS_ENG FROM STUDENT;

------------- GROUP BY ------------

Select location, count(firstname) as student_count from STUDENT group by LOCATION;

-------------- GROUP BY WITH CONDITION

Select location, count(firstname) as student_count from STUDENT group by LOCATION HAVING count(firstname) > 1;

SELECT * FROM STUDENT;

