-- TO CREATE TABLES WITH COLUMN NAMES
CREATE TABLE PRACTICE(NAME VARCHAR(20), AGE INT, LOCATION VARCHAR(10));

-------- TO INSERT VALUES WE HAVE 2 TYPES 

--- 1 - FOR ALL COLUMNS
INSERT INTO PRACTICE VALUES ('UTH', 56, 'GOREGAON'), ('OKD', 32, 'DADAR'), ('ZYS', 45, 'ANDHERI');

--- 2 - FOR SPECIFIC COLUMN INSERT 
INSERT INTO PRACTICE (NAME, LOCATION) VALUES ('PLM', 'VILE PARLE'), ('HFG', 'VIRAR'); 

-- GET THE DATA
SELECT * FROM PRACTICE;
----------------- DELETE | DROP | TRUNCATE ------------------------------

--- DELETE IS USED TO DELETE A PARTICULAR DATA FROM THE TABLE

-- SINGLE CONDITION

DELETE FROM GARGI WHERE ROLLNO = 34;

-- MULTIPLE CONDITION

DELETE FROM GARGI WHERE ROLLNO = 34 AND AGE = 45;

----- TRUNCATE  - USED WHEN WE HAVE TO DELETE ALL THE DATA FROM A TABLE WITHOUT DELETING ITS STRUCTURE

TRUNCATE TABLE GARGI;

----- DROP - USED TO DELETE EVERYTHING [TABLE AS WELL AS DATA]

DROP TABLE GARGI;

---------------------------------------------------------------------

--------------- ALTER - TO MAKE CHANGES IN THE TABLE STUCTURE

--- ADD COLUMNS

ALTER TABLE STUDENT ADD DEMO1 INT, DEMO2 VARCHAR(20);

--- UPDATE COLUMN VALUES

-- FOR ALL

UPDATE STUDENT SET DEMO1 = 12, DEMO2 = 'HELLOE'

-- FOR PARTICULAR

UPDATE STUDENT SET DEMO1 = 23, DEMO2 = 'ABCD' WHERE ROLLNO = 45;

---ALTER - TO DELETE COLUMNS FROM TABLE

ALTER TABLE STUDENT DROP COLUMN DEMO1,DEMO2;

----------- DISTINCT - TO GET THE UNIQUE VALUES FROM A COLUMS

SELECT DISTINCT(DIV) FROM STUDENT;

-----------  BETWEEN  | AND  | OR

SELECT * FROM STUDENT WHERE ENG BETWEEN 60 AND 80;

SELECT * FROM STUDENT WHERE ENG NOT BETWEEN 60 AND 80;

SELECT * FROM STUDENT WHERE LOCATION = 'DADAR' AND (ENG BETWEEN 60 AND 80) AND ROLLNO = 67;

SELECT * FROM STUDENT WHERE LOCATION = 'DADAR' OR (ENG BETWEEN 60 AND 80) OR ROLLNO = 67;

-------------------- IN | NOT IN

SELECT * FROM STUDENT WHERE LOCATION IN ('GOREGAON', 'VIRAR', 'DADAR');

SELECT * FROM STUDENT WHERE LOCATION NOT IN ('GOREGAON', 'VIRAR', 'DADAR');

SELECT * FROM STUDENT WHERE STD IN (5,4,8);

SELECT * FROM STUDENT WHERE STD NOT IN (5,4,8);


------------------- LIKE 

SELECT * FROM STUDENT WHERE FIRSTNAME LIKE 'A%';

SELECT * FROM STUDENT WHERE FIRSTNAME LIKE '%M';

SELECT * FROM STUDENT WHERE FIRSTNAME LIKE '%H%';

SELECT * FROM STUDENT WHERE FIRSTNAME LIKE '_A%';

SELECT * FROM STUDENT WHERE FIRSTNAME LIKE '%A_';

SELECT * FROM STUDENT WHERE FIRSTNAME LIKE '%A__';


